[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi (>=0.115.12,<0.116.0)",
    "uvicorn (>=0.34.2,<0.35.0)",
    "sqlalchemy (>=2.0.41,<3.0.0)",
    "aiosqlite (>=0.21.0,<0.22.0)",
    "google-api-python-client (>=2.169.0,<3.0.0)",
    "gspread (>=6.2.1,<7.0.0)",
    "pydantic (>=2.11.4,<3.0.0)",
    "greenlet (>=3.2.2,<4.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
ruff = "^0.11.10"
httpx = "^0.28.1"
alembic = "^1.15.2"
pytest-asyncio = "^0.26.0"

[tool.pytest.ini_options]
python_files = "tests.py test_*.py *_test.py"
asyncio_mode = "auto"
pythonpath = ["."]

[tool.ruff]
line-length = 88
src = ["app", "tests"]
# Select a base set of rules explicitly, e.g., pycodestyle (E) and Pyflakes (F)
# You can add more rule codes as needed.
# select = ["E", "F"]
# For a stricter set, consider something like:
# select = ["A", "B", "C4", "E", "F", "I", "N", "PLC", "PLE", "PLR", "PLW", "RUF"]

# You can also exclude files or directories if needed
# extend-exclude = [
#    "alembic/versions/*", # Often auto-generated, might not need strict linting
# ]

