"""create_initial_tables

Revision ID: 8b367832b1d9
Revises: 
Create Date: 2025-05-18 16:57:33.511457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b367832b1d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('foundation_date', sa.DateTime(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('phase', sa.Enum('PRE_SEED', 'SEED', 'EARLY', 'GROWTH', 'EXPANSION', 'EXIT', name='companyphaseenum'), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('crunchbase', sa.String(), nullable=True),
    sa.Column('glassdoor', sa.String(), nullable=True),
    sa.Column('short_description', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('related_articles', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_table('job_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('JOB_BOARD', 'RECRUITER', 'COMPANY_WEBSITE', 'NETWORKING', 'REFERRAL_PROGRAM', 'OTHER', name='jobsourcetypeenum'), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('short_description', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_sources_id'), 'job_sources', ['id'], unique=False)
    op.create_index(op.f('ix_job_sources_name'), 'job_sources', ['name'], unique=True)
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('job_url', sa.String(), nullable=False),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('location_country', sa.String(), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=True),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', 'TEMPORARY', 'VOLUNTEER', name='employmenttypeenum'), nullable=True),
    sa.Column('used_resume', sa.String(), nullable=True),
    sa.Column('cover_letter_file_path', sa.String(), nullable=True),
    sa.Column('requested_salary_min', sa.Integer(), nullable=True),
    sa.Column('requested_salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(), nullable=True),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('CONSIDERING', 'NOT_PURSUING', 'APPLIED', 'IN_PROGRESS', 'WITHDRAWN', 'OFFERED', 'REJECTED', 'EXPIRED', name='applicationstatusenum'), nullable=False),
    sa.Column('discovered_through_id', sa.Integer(), nullable=False),
    sa.Column('applied_through_text', sa.String(), nullable=True),
    sa.Column('referral', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['discovered_through_id'], ['job_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_applications_id'), 'job_applications', ['id'], unique=False)
    op.create_table('application_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_application_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('APPLICATION_SUBMITTED', 'RESUME_VIEWED', 'SCREENING_CALL_SCHEDULED', 'SCREENING_CALL_COMPLETED', 'TECHNICAL_INTERVIEW_SCHEDULED', 'TECHNICAL_INTERVIEW_COMPLETED', 'HR_INTERVIEW_SCHEDULED', 'HR_INTERVIEW_COMPLETED', 'TAKE_HOME_ASSIGNMENT_SENT', 'TAKE_HOME_ASSIGNMENT_SUBMITTED', 'FINAL_INTERVIEW_SCHEDULED', 'FINAL_INTERVIEW_COMPLETED', 'FOLLOW_UP_SENT', 'THANK_YOU_NOTE_SENT', 'OFFER_RECEIVED', 'OFFER_TERMS_DISCUSSED', 'OFFER_ACCEPTED', 'OFFER_DECLINED', 'APPLICATION_WITHDRAWN', 'REJECTION_RECEIVED', 'FEEDBACK_REQUESTED', 'FEEDBACK_RECEIVED', 'NETWORKING_CALL', 'INFORMATIONAL_INTERVIEW', 'NOTE_ADDED', name='applicationeventtypeenum'), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('participants', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_events_id'), 'application_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_events_id'), table_name='application_events')
    op.drop_table('application_events')
    op.drop_index(op.f('ix_job_applications_id'), table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_index(op.f('ix_job_sources_name'), table_name='job_sources')
    op.drop_index(op.f('ix_job_sources_id'), table_name='job_sources')
    op.drop_table('job_sources')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
